
name: Download Degree Day Data

on:
  schedule:
    - cron: '59 4 * * *'     # Runs daily at 4:59 UTC = 11:59 PM EST (UTC-5)
  workflow_dispatch:          # Optional: allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run degree day script
        run: python scripts/hdd_cdd_daily.py

      - name: Upload data output
        uses: actions/upload-artifact@v4
        with:
          name: degree-day-csv
          path: data/*.csv
